const {
  INGEST_MONGO_USERNAME,
  INGEST_MONGO_PASSWORD,
  INGEST_MONGO_HOSTNAME,
  INGEST_MONGO_CONTAINER_PORT,
  INGEST_MONGO_DATABASE,
} = process.env

module.exports.datastores = {
  default: {
    adapter: 'sails-mongo',
    url: `mongodb://${INGEST_MONGO_USERNAME}:${INGEST_MONGO_PASSWORD}@${INGEST_MONGO_HOSTNAME}:${INGEST_MONGO_CONTAINER_PORT}/${INGEST_MONGO_DATABASE}`
  }
};
